   if(modelno=='2KD'){
                   $('#2KD').show();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                      
                      
              }
			  
			  //GFV
			    if(modelno=='GFV'){
                   $('#2KD').hide();
                   $('#GFV').show();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                      
                      
              }
			  
			  //gz
			  
			   if(modelno=='GZ'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').SHOW();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
					 
					 
					 //WAH
               if(modelno=='WAH'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').show();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
              //vxs
			   if(modelno=='VXS'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').show();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
              
			  //VAR
			  
			    if(modelno=='VAR'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').show();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
              
			    if(modelno=='SPD'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').show();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
              //sct
			    if(modelno=='SCT'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').show(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
              //RAD
			     if(modelno=='RAD'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').show();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }  

//SCB
					 if(modelno=='SCB'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').show();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
         
//NXG

    	 if(modelno=='NXG'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').show();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
               
			   
			   //mst
			   if(modelno=='HP FILTER ELEMENT'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').show();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
              
			     //mst
			   if(modelno=='HP FILTER'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').show();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
              //hln
			    if(modelno=='HLN'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').show();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
        
	//hld
		if(modelno=='HLD'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').show();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
          
		  
		 //dct 
		  if(modelno=='DCT'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').show();
                     }
           
		   //gzf
		   if(modelno=='GZF'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').show();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
 //ect          
if(modelno=='ECT'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').show();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
           
    //gas       
if(modelno=='GAS'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').show();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
     //ACC       
if(modelno=='ACC'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').show();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
      
//AT
	  if(modelno=='AT'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').show();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
      

//CHI MINI
	  if(modelno=='CHI MINI'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').show();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
		//cht lh			 
        if(modelno=='CHT NEXTGEN LH'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').show();
                   $('#DCT').hide();
                     }
          //nex gen hh 
 if(modelno=='CHT NEXTGEN HH'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').show();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
					 
					 //gct
            if(modelno=='GCT'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').hide();
                   $('#GCT_ECHO').show();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
           
 if(modelno=='GZF CATRIDGES'){
                   $('#2KD').hide();
                   $('#GFV').hide();
                   $('#GZ').hide();
                   $('#WAH').hide();
                   $('#VXS').hide();
                   $('#VAR').hide();
                   $('#SPD').hide();
                   $('#SCT').hide(); 
				   $('#RAD').hide();
                   $('#SCB').hide();
                   $('#NXG').hide();
                   $('#MST').hide();
                   $('#hpfilter_ele').hide();
                   $('#hpfilter').hide();
                   $('#HLN').hide();
                   $('#HLD').hide();
                   $('#GZF_CATRIDGES').show();
                   $('#GCT_ECHO').hide();
                   $('#GZF').hide();
                   $('#ECT').hide();
                   $('#GAS').hide();
                   $('#ACC').hide();
                   $('#AT').hide();
                   $('#CHT_MINI').hide();
                   $('#CHT_NEXTGEN_HH').hide();
                   $('#CHT_NEX_GENLH').hide();
                   $('#DCT').hide();
                     }
           

		   }